### ISSUE TITLE
1.9 Feature Update

### ISSUE THREAD

**Issue by Plastix** [Plastix/Plast-Pack#56]
**Todo:**
- [x] Update Command block textures
- [x] Update new boat textures and item sprites
- [x] Tweak off-hand GUI layout
- [x] Misc language file updates
- [x] Tweak `bars.png`

**Proposals:**
- [ ] Tweak Elyra texture
- [x] Tweak shield texture

**Comment by Plastix** [comment]
@Brottweiler Any other ideas?

**Comment by Brottweiler** [comment]
- Potentially tweak frosted ice (if we want it to look different than current)
- Path block?
- New zombie villagers won't match the default/old zombie villager. Either make them look same, or wait for zebragrrl?
- Custom shield that blocks less of the screen?

**Comment by Brottweiler** [comment]
`assets/minecraft/textures/gui/bars.png` is a new file containing bars of various kinds (similar to bossbar). I guess they are for map making, but OCN uses this instead of bossbar.

The background of the boss bar, xp bar and horse bar is in `icons.png` and have transparent background, and custom foreground. The bars in `bars.png` looks similar to them, so we can tweak those.

**Comment by Plastix** [comment]
Obsolete issue.
