### ISSUE TITLE
1.14 Feature Update

### ISSUE THREAD

**Issue by Brottweiler** [Plastix/Plast-Pack#62]
# Todo
- [x] Language string updates
- [x] Unstitch particles (including explosion)
- [x] Unstitch paintings
- [x] Unstitch effect icons
- [x] Update sign textures to match planks
- [x] Tweak new dyes to match the others
- [ ] New Stevian Villagers textures for new villagers
- [x] Tweak new textures using planks to look more smooth (like regular planks)

# Proposals
- [x] Tweak crossbow (skinny & status indicator)
- [ ] Redo the planks to match new default planks (then make them more smooth)?

**Comment by Brottweiler** [comment]
Since Minecraft now ships with a new set of default textures, there will be some caveats; 

- some stone ores like lapis ore won't match the new stone
- some sandstone faces like red chiseled sandstone won't match other sandstone
- mossy cobble won't match regular cobble
- planks might look bad together with other blocks

There are a few options though

1. Make sure players use **Programmer Art**. Then everything will work...
2. Add the necessary textures from **Programmer Art** so stuff doesn't look weird...
3. Tweak the necessary textures so they match with the new textures. 

Regarding option 3 we would for example be replacing the stone part of all ores to match the new stone texture, and try to use the new planks and make them smoother.
